name: Build HybridPedestal for 1.21.x

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build for multiple versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1.21.1, 1.21.2, 1.21.3, 1.21.4]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Verify Java version
        run: java -version

      - name: Set Paper API version
        run: |
          echo "Building for Paper ${MATRIX_VERSION}"
          # Nếu dùng Maven, bạn có thể pass -DpaperVersion=${MATRIX_VERSION}
          # hoặc chỉnh pom.xml động trước khi build
          mvn versions:set-property -Dproperty=paper.version -DnewVersion=${{ matrix.version }}

      - name: Build plugin
        run: mvn clean package -DskipTests

      - name: List built files
        run: ls -lh target/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HybridPedestal-${{ matrix.version }}-JAR
          path: target/*.jar
